package com.example.barbershop;

import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.CountDownTimer;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.Locale;

public class PaymentActivity extends AppCompatActivity {

    private static final long PAYMENT_WINDOW_MILLIS = 15 * 60 * 1000L;
    private static final long ONE_SECOND_MILLIS = 1000L;

    private CountDownTimer paymentCountdownTimer;
    private String transferContent;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_payment);

        bindTemporaryPaymentDetails();
        setupActions();
        startCountdown();
    }

    @Override
    protected void onDestroy() {
        if (paymentCountdownTimer != null) {
            paymentCountdownTimer.cancel();
        }
        super.onDestroy();
    }

    private void bindTemporaryPaymentDetails() {
        Intent intent = getIntent();
        String serviceName = readStringExtra(intent, "selectedServiceName", "Haircut");
        String addonServiceName = readStringExtra(intent, "addonServiceName", "Classic Cut");
        String barberName = readStringExtra(intent, "selectedBarberName", "Michael");
        String dateLabel = readStringExtra(intent, "selectedDateLabel", "Tomorrow, May 25, 2025");
        String startTime = readStringExtra(intent, "selectedStartTime", "2:00 PM");
        int durationMinutes = intent.getIntExtra("totalDurationMinutes", 45);
        double totalPrice = intent.getDoubleExtra("totalPrice", 25.0);
        String amount = readStringExtra(intent, "amount", String.format(Locale.US, "$%.2f", totalPrice));

        ((TextView) findViewById(R.id.textPaymentBarberInitial)).setText(getInitial(barberName));
        ((TextView) findViewById(R.id.textPaymentBarber)).setText(barberName);
        ((TextView) findViewById(R.id.textPaymentService)).setText(
                String.format(Locale.US, "%s, %s", serviceName, addonServiceName)
        );
        ((TextView) findViewById(R.id.textPaymentDate)).setText(dateLabel);
        ((TextView) findViewById(R.id.textPaymentTime)).setText(
                String.format(Locale.US, "%s - %d min", startTime, durationMinutes)
        );
        ((TextView) findViewById(R.id.textPaymentAmount)).setText(amount);

        transferContent = getString(R.string.payment_transfer_content_value);
        ((TextView) findViewById(R.id.textPaymentBankName)).setText(rowText(
                getString(R.string.payment_bank_name),
                getString(R.string.payment_bank_name_value)
        ));
        ((TextView) findViewById(R.id.textPaymentAccountNumber)).setText(rowText(
                getString(R.string.payment_account_number),
                getString(R.string.payment_account_number_value)
        ));
        ((TextView) findViewById(R.id.textPaymentAccountName)).setText(rowText(
                getString(R.string.payment_account_name),
                getString(R.string.payment_account_name_value)
        ));
        ((TextView) findViewById(R.id.textPaymentTransferContent)).setText(rowText(
                getString(R.string.payment_transfer_content),
                transferContent
        ));

        // TODO: Replace the QR placeholder with QR data generated by PaymentService or the payment provider.
    }

    private void setupActions() {
        findViewById(R.id.buttonBack).setOnClickListener(v -> finish());
        findViewById(R.id.buttonPaymentMore).setOnClickListener(v ->
                Toast.makeText(this, R.string.payment_security_note, Toast.LENGTH_SHORT).show()
        );
        findViewById(R.id.buttonCopyTransferContent).setOnClickListener(v -> copyTransferContent());
        findViewById(R.id.buttonIHavePaid).setOnClickListener(v -> {
            // Demo-only confirmation. Replace with PaymentService verification before production.
            ((TextView) findViewById(R.id.buttonIHavePaid)).setText(R.string.payment_demo_confirmed_action);
            findViewById(R.id.buttonIHavePaid).setEnabled(false);
            Toast.makeText(this, R.string.payment_demo_confirmed, Toast.LENGTH_SHORT).show();
        });
        findViewById(R.id.buttonCheckStatus).setOnClickListener(v -> {
            Toast.makeText(this, R.string.payment_demo_confirmed, Toast.LENGTH_SHORT).show();
        });
    }

    private void startCountdown() {
        paymentCountdownTimer = new CountDownTimer(PAYMENT_WINDOW_MILLIS, ONE_SECOND_MILLIS) {
            @Override
            public void onTick(long millisUntilFinished) {
                long totalSeconds = millisUntilFinished / ONE_SECOND_MILLIS;
                long minutes = totalSeconds / 60;
                long seconds = totalSeconds % 60;
                String timeLeft = String.format(Locale.US, "%02d:%02d", minutes, seconds);
                ((TextView) findViewById(R.id.textPaymentCountdown)).setText(
                        getString(R.string.payment_countdown_format, timeLeft)
                );
            }

            @Override
            public void onFinish() {
                ((TextView) findViewById(R.id.textPaymentCountdown)).setText(
                        getString(R.string.payment_countdown_format, "00:00")
                );
            }
        };
        paymentCountdownTimer.start();
    }

    private void copyTransferContent() {
        ClipboardManager clipboardManager = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
        if (clipboardManager != null) {
            clipboardManager.setPrimaryClip(ClipData.newPlainText(
                    getString(R.string.payment_transfer_content),
                    transferContent
            ));
            Toast.makeText(this, R.string.payment_copy_success, Toast.LENGTH_SHORT).show();
        }
    }

    private String readStringExtra(Intent intent, String key, String fallback) {
        String value = intent.getStringExtra(key);
        return value == null || value.trim().isEmpty() ? fallback : value;
    }

    private String getInitial(String value) {
        return value == null || value.trim().isEmpty()
                ? "A"
                : value.trim().substring(0, 1).toUpperCase(Locale.US);
    }

    private String rowText(String label, String value) {
        return String.format(Locale.US, "%s  %s", label, value);
    }
}
